### ISSUE TITLE
Running TopNotify causes hitches while moving my mouse in Final Fantasy XIV

### ISSUE THREAD

**Issue by amasover** [SamsidParty/TopNotify#21]
I noticed that while this application is running, I get frequent and severe hitching while moving my mouse in Final Fantasy XIV.

I used Special K's framepacing graph to capture this phenomenon.

Normal:

![FINAL FANTASY XIV 2024-08-24 01ː18ː56](https://github.com/user-attachments/assets/7c0c3d6a-bf76-4930-b1f0-573943bef01b)

Moving mouse while TopNotify is open:

![FINAL FANTASY XIV 2024-08-24 01ː17ː33](https://github.com/user-attachments/assets/f96d1152-49d9-492d-ab21-d2f83d7dc20a)

I tried changing the polling rate of my mouse, but that had no effect. Only closing TopNotify seems to help.

I am running Windows 11 24H2 OS Build 26100.1586 (Windows Insider Release Preview channel).

**Comment by SamsidParty** [comment]
When you say TopNotify is running, do you mean while the GUI is running, or the background process is running?
Is there a certain pattern to the hitches? i.e: The hitches are a certain distance apart.
And another question, is Microsoft Teams running as well?

**Comment by amasover** [comment]
* I get the hitches while running only the background process. Whether the GUI is open doesn't seem to make a difference. Closing TopNotify by right-clicking the system tray icon and selecting quit causes the issue to go away.
* There is a pattern to the hitches -- those spikes in the screenshot seem to happen very regularly. Each spike occurs after a bit less than a second. I'd need a different monitoring tool with logging or time units to get more accurate than that.
* Teams is not installed on my PC.

**Comment by SamsidParty** [comment]
I see, since the teams interceptor is ruled out, it might be something else.
Some background work in TopNotify occurs every 500ms, do you think that the hitches line up with that?

**Comment by adkeyz** [comment]
I noticed the same thing today and had to uninstall, games are completely unplayable with TopNotify running.

This isn't just in a game either, my PC would hitch the same just moving a window around my desktop with TN ruinning.

It is a consistent lag spike, it felt like every second or two (im not sure of the exact timing but it is an exact distance apart each time like a pulse almost) my PC would "freeze" for a split second.

**Comment by SamsidParty** [comment]
You're right, I didn't notice until you pointed it out, I do in fact notice hitching when dragging windows.
I will look into it and fix ASAP.

**Comment by Skazzy3** [comment]
I am able to replicate this using Call of Duty Modern Warfare 3, where it seems every second exactly, the game will hitch.

**Comment by SamsidParty** [comment]
A new update has been released, not sure if it fixes it but it's best to try.
Somehow I'm not able to reproduce this bug anymore, which is interesting.

**Comment by amasover** [comment]
I just tried the newest version (2.4.3), and unfortunately I'm still seeing the hitches.

**Comment by SamsidParty** [comment]
That's a shame, do you think you could send a screenshot of the settings you're using?
Also, is your system language set to english?

**Comment by Skazzy3** [comment]
The 2.4.3 version has not resolved the issue in Call of Duty either sadly.

**Comment by amasover** [comment]
My system language is English, though I have several language packs installed (Japanese, Spanish, Chinese, and Korean).

Screenshot of my TopNotify UI:
![image](https://github.com/user-attachments/assets/2ce934cd-261b-469e-a262-03980f45a16d)

**Comment by SamsidParty** [comment]
I see, well I'm gonna try to reproduce this issue in a virtual machine, as long as I can reliably reproduce the issue I can fix it.

**Comment by SamsidParty** [comment]
I know this might sound silly, but can you try downgrading to version [2.3.7](https://github.com/SamsidParty/TopNotify/releases/download/2.3.7/TopNotify.Msix)?
That was the last version before the extra bloat, and if that version works it might lead me to the cause of the issue.

**Comment by amasover** [comment]
I do not see hitching with 2.3.7

**Comment by SamsidParty** [comment]
Perfect! In that case, maybe it is the Microsoft Teams interceptor after all, 
I will see if I can fix it, worst case I can add a switch to disable MS teams interception entirely.

**Comment by SamsidParty** [comment]
One last question (for now), do any of you have any antivirus software installed except for Windows Defender?
The microsoft teams interceptor has some code that may be deemed suspicious (to inject the ms-teams.exe process),
and that can cause antivirus software to lag the system. If so, try disabling the AV and see if the hitches still happen.

Thanks everyone for your patience and cooperation.

**Comment by amasover** [comment]
I don't have any antivirus besides Windows Defender.

And the game I'm playing doesn't come with any local anti-cheat.

**Comment by Skazzy3** [comment]
Personally I do not use anything other than Windows Defender (2.3.7 does not cause the hitching in game for me as well)

**Comment by SamsidParty** [comment]
I have real quick compiled a version with Teams support disabled, [2.4.3-no-teams](https://github.com/SamsidParty/TopNotify/releases/tag/2.4.3-no-teams)
Let me know on your own time if this fixes the stuttering issues.

**Comment by amasover** [comment]
I installed that beta version you compiled, and I do see stuttering / hitching.

**Comment by SamsidParty** [comment]
I see, I will look into it tomorrow as I'm busy today.

**Comment by SamsidParty** [comment]
I have released another beta version, please check if that fixes it.

**Comment by amasover** [comment]
I just tried 2.44 beta 1, and it still has the stuttering issue.

As a sanity test, I went back to 2.3.7 again, and still no hitching/stuttering with that version.

Thanks again for all your time and effort looking into this!

**Comment by SamsidParty** [comment]
I think I've found the issue, I believe it's because of a new windows display API library that has replaced the old one. I'll see what I can do about it.

**Comment by SamsidParty** [comment]
Please try [2.4.4-beta2](https://github.com/SamsidParty/TopNotify/releases/tag/2.4.4-beta2), the scaling system has been rewritten (yet again) to remove the dependency.

**Comment by Skazzy3** [comment]
Unfortunately, at least personally, I am still seeing the hitching issue with 2.4.4-beta2

**Comment by amasover** [comment]
2.4.4-beta2 seems to not have the same issue for me, personally. Although I'm also having more difficulty reproducing it right now -- for whatever reason the hitching doesn't seem to be as bad in general. But I went back to 2.43 and I still see the regular (every couple seconds) variance in the frametime graph, where with 2.4.4-beta2 the graph seems completely smooth to me.

**Comment by SamsidParty** [comment]
Ok, I have made some more optimizations, so hopefully it will work for @Skazzy3 as well in the final release.
I still have to finish up the new notification sounds feature in 2.4.4, and then it'll be released.

**Comment by Skazzy3** [comment]
I apologize, I seemed to have launched the wrong version when testing. I can confirm that I'm not seeing those stuttering issues on 2.4.4-beta2. Looking forward to the full release.

**Comment by SamsidParty** [comment]
Perfect! @adkeyz is it fixed for you as well?

**Comment by SamsidParty** [comment]
Version 2.4.4 is now available, it fixes most performance issues. Please update TopNotify.
If the issue is fixed, please update any bad reviews.
