### ISSUE TITLE
Can't Change Sounds

### ISSUE THREAD

**Issue by Galthariel** [SamsidParty/TopNotify#40]
While I can see and the app the sounds options when I click in any of it another window open with the words SELECT SOUND but doesn't allow me to actual change anything

**Comment by SamsidParty** [comment]
Can you send a screenshot please?

**Comment by Galthariel** [comment]
There you go. Hope the explanation makes sense and helps.

![2024-11-28_17-11-23](https://github.com/user-attachments/assets/3c69e044-6867-48ed-b8a3-05af4c3757cf)

**Comment by SamsidParty** [comment]
I see, if you press F12 it will open dev tools, does it show any errors when you are on the "Select Sound" page?

**Comment by Galthariel** [comment]
The only "error" I was able to see was related to the favicon and since I'm not a dev I really don't know if has anything to do with the problem and/or if there is any other places I should be looking. Here is the screenshot

![2024-11-29_12-37-26](https://github.com/user-attachments/assets/abb89a4f-77c2-4ddd-8413-a08cc6da19a2)

**Comment by Galthariel** [comment]
Hello,

Any updates? It's a bug? it's a USER lack of knowledge on how to do it? Anything I can try on my end?

Thanks

**Comment by SamsidParty** [comment]
I apologize for the lack of communication, I am at the airport right now and still have to look into it.

**Comment by Galthariel** [comment]
No worries. Safe travels :-)

**Comment by SamarthMP** [comment]
Could you try pressing F2, pressing "open app folder", then deleting Settings.json and restarting TopNotify?

**Comment by Galthariel** [comment]
Tried...deleted the Settings.json, and I know it because when I restarted TopNotify the position of the notification reset and as well the transparency. However, the issue persists and still shows a blank page when I try to change the sounds :-(

**Comment by Galthariel** [comment]
nope...I don't...for a long time since Spotify came out :-)

**Comment by SamsidParty** [comment]
Then I'm not sure how this is happening... I'll have to investigate

**Comment by SamarthMP** [comment]
Hello, I apologize for the late response. Can you please try the latest [beta](https://github.com/SamsidParty/TopNotify/releases/tag/3.0.0-beta1) version?

**Comment by Galthariel** [comment]
> Hello, I apologize for the late response. Can you please try the latest [beta](https://github.com/SamsidParty/TopNotify/releases/tag/3.0.0-beta1) version?

Just installed, and the Beta didn't override the stable release, instead, I had both, which I actually prefer since it's for test purposes. Bad news is that every time a click the Beta in the tray, the window shows for a few milliseconds and disappears. It doesn't crash because it's still there in the tray. Before you ask me, no, the stable and Beta aren't running at the same time. I closed the stable before trying the Beta

**Comment by Galthariel** [comment]
Windows 11 and just tried the Beta 2 since first time I got Beta 1. Same issue

**Comment by SamsidParty** [comment]
Hmm I'm not sure what caused the instant windows crashing. I'll have to experiment with it.

**Comment by Galthariel** [comment]
> Hmm I'm not sure what caused the instant windows crashing. I'll have to experiment with it.

Like I said...TopNotify itself didn't crash, only the window disappears after a click the systray icon

**Comment by SamsidParty** [comment]
TopNotify creates a separate process for the settings panel, so that's what crashed. I think the issue is related to reading your music folder. Do you have any antivirus settings that may affect this?

**Comment by SamarthMP** [comment]
I see, if you have time can you please run procmon on TopNotify (if you know how). It'll really make fixing this easier.

**Comment by Galthariel** [comment]
I do have Procmon from Sysinternals installed but I don't know how to use it to help you identify the problem

What I found in EventViwer was this

0x8007012B: Cannot create the process for package 55968SamsidGameStudios.TopNotifyBeta_3.0.0.0_x64__7z56rv9757nb0 because an error was encountered while launching. [LaunchProcess]

I also have ProcessLasso and while I kept open I have click on the TopNotify systray icon and a new TopNotify show up and immediately disappeared and I think this is what you mentioned before about creating a new process that is crashing

if you want me to use Procmon you will have to walk me through

**Comment by Galthariel** [comment]
Here is another event

Application: TopNotify.exe
CoreCLR Version: 9.0.24.52809
.NET Version: 9.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at TopNotify.Common.Program.<>c.<Main>b__2_1(Process p)
   at System.Linq.Enumerable.ArrayWhereIterator`1.TryGetFirst(Boolean& found)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at TopNotify.Common.Program.Main(String[] args)

**Comment by SamarthMP** [comment]
New beta [3](https://github.com/SamsidParty/TopNotify/releases/tag/3.0.0-beta3) is available. I have attempted to fix these errors. I have also added a dedicated error message box so we can pinpoint the issues related to the sound changing. I appreciate your patience. 

Note: you'll have to quit and uninstall the previous beta first otherwise windows won't let you install the new one.

**Comment by Galthariel** [comment]
Just installed and the issue remains...and yes, I did uninstall the previous Beta.

Weird is that now Events doesn't show anything for Beta 3, but I found 2 additional events from the previous ones

Application: TopNotify.exe
CoreCLR Version: 8.0.1124.51707
.NET Version: 8.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at TopNotify.Common.Program.<>c.<Main>b__2_1(Process p)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Linq.Enumerable.<Any>g__WithEnumerator|36_0[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at TopNotify.Common.Program.Main(String[] args)

_____________________________________________________________________________________________________________________

Faulting application name: TopNotify.exe, version: 1.0.0.0, time stamp: 0x67110000
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffd8f454211
Faulting process id: 0x0x61EC
Faulting application start time: 0x0x1DB8AC4BB634D23
Faulting application path: C:\Program Files\WindowsApps\55968SamsidGameStudios.TopNotify_2.6.1.0_x64__r9j5xrxak4zje\TopNotify.exe
Faulting module path: unknown
Report Id: a82bc86f-c9ff-485b-a292-968cccfb8b58
Faulting package full name: 55968SamsidGameStudios.TopNotify_2.6.1.0_x64__r9j5xrxak4zje
Faulting package-relative application ID: TopNotify

**Comment by Galthariel** [comment]
by the issue remains I'm referring to when I click the systray icon a window shows up and immediately disappears

**Comment by Galthariel** [comment]
Here is another one

The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user R2-D2\Gabriel SID (S-1-5-21-2395807674-896685339-92284077-1001) from address LocalHost (Using LRPC) running in the application container 55968SamsidGameStudios.TopNotify_2.6.1.0_x64__r9j5xrxak4zje SID (Unavailable). This security permission can be modified using the Component Services administrative tool.

**Comment by SamarthMP** [comment]
Interesting, it should have shown a message box when it crashes, this indicates a crash within the C++ code instead of the C# code. Those old events are from an old version (TopNotify 3.0.0+ uses .NET 9 not 8) I'll look into the other error you are getting, it does seem like a C++ error.

**Comment by SamarthMP** [comment]
Well unfortunately I couldn't find any errors in my testing, so I'll show you how to use procmon. 

First open procmon.
When you open procmon, it'll show you a filters panel. Add a filter that says if "Process name" "contains" "TopNotify" then "include"
Make sure there aren't any other non-default filters.

![Image](https://github.com/user-attachments/assets/d6694d90-856c-4724-87a9-7c9140aa0c16)

Press "Add" -> "Apply" -> "Ok"

Now double click the TopNotify tray icon, wait for the window to pop up and crash, then wait a few seconds for procmon to collect all the logs. 

Finally, do "File" -> "Save" -> ".PML", and send the logs to me :)

**Comment by Galthariel** [comment]
There you go

[Logfile.zip](https://github.com/user-attachments/files/19040164/Logfile.zip)

**Comment by SamarthMP** [comment]
Yup, as I expected, the crash is caused by attempting to read `C:\Users\Gabriel\Music` and failing. In the previous version it would show a blank screen, but this time it's causing a full on crash because some logic changed. Can you double check that `C:\Users\Gabriel\Music` exists and the permissions on it are valid?

**Comment by Galthariel** [comment]
\Users\Gabriel\Music doesn't exist since I always change the location to a different drive which in my case is O:\Music

Also, I don't know if it is important or not but for sounds specifically I use the C:\Windows\Media folder which is the original folder that Windows sounds are storage and where I save new sound schemes as well.

**Comment by SamarthMP** [comment]
No problem, in this case this is an easy fix, I'll just check if it exists. It was incorrect of me to assume that the directory exists ;)
Is it ok if you create that folder temporarily and double check if all the issues are gone? After that I'll upload a fixed build to github and the MS store.

**Comment by Galthariel** [comment]
Yep, it does works now, and I can even access the part where I can pick a new sound however I didn't see an option to "browse" for a new sound and instead only 6 Windows options (notify11, 10, 7, and etc.)

**Comment by Galthariel** [comment]
ohhh...probably because C:\user\XXXX\Music is empty :-P

**Comment by SamarthMP** [comment]
>  I didn't see an option to "browse" for a new sound and instead only 6 Windows options (notify11, 10, 7, and etc.)

Yup, the idea was for you to simply drop your sounds into the music folder and it will detect them. That was the root cause of the issue. Now that you point it out it does make way more sense to simply browse or drag/drop, may add in future.

>  ohhh...probably because C:\users\XXXX\Music is empty :-P

More like because it didn't exist at all, I have pushed the fixes and will submit to the store ASAP.

**Comment by Galthariel** [comment]
I just got an auto update from MS Store and the issue I mentioned before is there (Settings opens and closes almost immediately) so I'm assuming you may have uploaded the wrong version because GitHub still shows 2.45 as the latest stable

**Comment by SamarthMP** [comment]
> I'm assuming you may have uploaded the wrong version because GitHub still shows 2.45 as the latest stable
Only on GitHub, since I haven't updated it on here yet (thanks for reminding me)

Sometimes the MS store auto updates don't work properly until you restart your computer (It will try to modify TopNotify.exe while it is running, which will corrupt it temporarily). Can you please try that? Also make sure to uninstall TopNotify beta as well before restarting.

**Comment by Galthariel** [comment]
> > I'm assuming you may have uploaded the wrong version because GitHub still shows 2.45 as the latest stable
> > Only on GitHub, since I haven't updated it on here yet (thanks for reminding me)
> 
> Sometimes the MS store auto updates don't work properly until you restart your computer (It will try to modify TopNotify.exe while it is running, which will corrupt it temporarily). Can you please try that? Also make sure to uninstall TopNotify beta as well before restarting.

Restart didn't work. Same issue and I wasn't using the Beta since yesterday :-)

And since I know you're going to ask here is the Procmon Log

[TopNotify_Logfile_03032025.zip](https://github.com/user-attachments/files/19054999/TopNotify_Logfile_03032025.zip)

**Comment by SamarthMP** [comment]
Ok looks like the same issue. What happened was I had cancelled the update on the MS store to fix this issue, then reuploaded the package with it fixed, but looks like the store still deployed the old version. The issue will definitely be fixed in the next version. For now, please use the temporary fix of creating an empty folder at `C:\Users\Gabriel\Music` until the next update. I apologize for the inconvenience.

**Comment by Galthariel** [comment]
No worries...happy to help to figure out the issue since it's a little app I love, and I'm sure plenty of people loves as well :-)

**Comment by Galthariel** [comment]
I can confirm that It's finally fixed. Next problem is the ability to browse for a sound, otherwise I will need to create the c:\users\xxxx\Music again to use it. I'm happy for now, so no rush need. Just want to let you know :-)
